WaMvTech/WaMvTech/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WaMvTech.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

WaMvTech/WaMvTech/Models/ComicBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WaMvTech.Models
{
    public class ComicBook
    {
        public int Id { get; set; }
        public string SeriesTitle { get; set; }
        public int IssueNumber { get; set; }
        public string DescriptionHtml { get; set; }
        public Artist[] Artists { get; set; }
        public bool Favorite { get; set; }

        public string DisplayText
        {
            get
            {
                return SeriesTitle + " #" + IssueNumber;
            }
        }

        public string CoverImageFileName
        {
            get
            {
                return SeriesTitle.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg";
            }
        }

    }
}

WaMvTech/WaMvTech/Controllers/ComicBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaMvTech.Models;
using WaMvTech.Data;

namespace WaMvTech.Controllers
{
    public class ComicBooksController : Controller
    {
        //: Properties
        private ComicBookRepository _comicBookRepository = null;


        //: Init Constructor
        public ComicBooksController()
        {
            _comicBookRepository = new ComicBookRepository();
        }


        public ActionResult Index()
        {

            var comicBooks = _comicBookRepository.GetComicBooks();

            return View(comicBooks);

        }

        public ActionResult Detail(int? Id)
        {

            if (Id == null)
            {
                return HttpNotFound();
            }

            //:This is using the GetComicBook method from the Repository to get the comic book equal to the id passed.
            var comicBook = _comicBookRepository.GetComicBook( (int)Id ); 
            
            return View(comicBook);            
        }
    }
}

WaMvTech/WaMvTech/Controllers/GridController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WaMvTech.Controllers
{
    public class GridController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

WaMvTech/WaMvTech/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WaMvTech.Controllers
{
    public class LandingController : Controller
    {
        //: Action Method
        public ActionResult Index()
        {
            return View();
        }
    }
}

WaMvTech/WaMvTech/Views/ComicBooks/Detail.cshtml
@model WaMvTech.Models.ComicBook

@{
    ViewBag.Title = Model.DisplayText;
    ViewBag.ShowBackBar = true;
}


        <h1>@Model.DisplayText</h1>

        <div class="row">
            <div class="col-md-3">
                <div class="well">
                    <h5><label>Series Title</label>@Model.SeriesTitle</h5>
                    <h5><label># Issues</label>@Model.IssueNumber</h5>
                    <h5><label>Favorite</label>@Model.Favorite ? "Yes" : "No"</h5>
                    @if (Model.Artists.Length > 0)
                    {
                        <h5>Artist: </h5>
                        <div>
                            <ul>
                                @foreach (var artist in Model.Artists)
                                {
                                    <li>@artist.Role : @artist.Name</li>
                                }
                            </ul>
                        </div>
                    }
                </div>
            </div>
            
        </div>

WaMvTech/WaMvTech/Views/ComicBooks/Index.cshtml
@model WaMvTech.Models.ComicBook[]

@{
    ViewBag.Title = "Comic Book";
}

<h2>@ViewBag.Title</h2>


<div class="row">
    @foreach (var comicBook in Model)
    {
        <div class="col-md-3">

            <h4>@Html.ActionLink(comicBook.DisplayText, "Detail", new { Id = comicBook.Id})</h4>

            <a href="@Url.Action("Detail", new { Id = comicBook.Id })">
                <img class="img-responsive" src="~/Images/@comicBook.CoverImageFileName" alt="@comicBook.DisplayText" />
            </a>

        </div>
    }
</div>

WaMvTech/WaMvTech/Views/Grid/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="grid">
    <main class="hexagon-container">

        <div class="hexagon color-css">
            <svg aria-labelledby="simpleicons-html5-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <title id="simpleicons-html5-icon">HTML5 icon</title>
                <path d="M1.5 0h21l-1.91 21.563L11.977 24l-8.564-2.438L1.5 0zm7.031 9.75l-.232-2.718 10.059.003.23-2.622L5.412 4.41l.698 8.01h9.126l-.326 3.426-2.91.804-2.955-.81-.188-2.11H6.248l.33 4.171L12 19.351l5.379-1.443.744-8.157H8.531z" />
            </svg>
        </div>

        <div class="hexagon color-vuejs">
            <svg aria-labelledby="simpleicons-html5-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <title id="simpleicons-html5-icon">HTML5 icon</title>
                <path d="M1.5 0h21l-1.91 21.563L11.977 24l-8.564-2.438L1.5 0zm7.031 9.75l-.232-2.718 10.059.003.23-2.622L5.412 4.41l.698 8.01h9.126l-.326 3.426-2.91.804-2.955-.81-.188-2.11H6.248l.33 4.171L12 19.351l5.379-1.443.744-8.157H8.531z" />
            </svg>
        </div>
    </main>
</div>

WaMvTech/WaMvTech/Views/Landing/Index.cshtml
@{
    ViewBag.Title = "Index";
}



<div class="row">




    <!-- Circle Animation and portal entry button -->
    <div class="col s8">
        <div id="content">

            <div class="outer-1">
                <div class="inner-1">&nbsp;</div>
                <div class="inner-2">&nbsp;</div>
                <div class="inner-3">&nbsp;</div>
            </div>

            <div class="portal_button">
                <a href="@Url.Action("Index","Grid")">
                    <div class="portal color-css">

                        <svg aria-labelledby="simpleicons-html5-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <title id="simpleicons-html5-icon">HTML5 icon</title>
                            <path d="M1.5 0h21l-1.91 21.563L11.977 24l-8.564-2.438L1.5 0zm7.031 9.75l-.232-2.718 10.059.003.23-2.622L5.412 4.41l.698 8.01h9.126l-.326 3.426-2.91.804-2.955-.81-.188-2.11H6.248l.33 4.171L12 19.351l5.379-1.443.744-8.157H8.531z" />
                        </svg>

                        <svg aria-labelledby="simpleicons-javascript-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title id="simpleicons-javascript-icon">JavaScript icon</title><path d="M0 0h24v24H0V0zm22.034 18.276c-.175-1.095-.888-2.015-3.003-2.873-.736-.345-1.554-.585-1.797-1.14-.091-.33-.105-.51-.046-.705.15-.646.915-.84 1.515-.66.39.12.75.42.976.9 1.034-.676 1.034-.676 1.755-1.125-.27-.42-.404-.601-.586-.78-.63-.705-1.469-1.065-2.834-1.034l-.705.089c-.676.165-1.32.525-1.71 1.005-1.14 1.291-.811 3.541.569 4.471 1.365 1.02 3.361 1.244 3.616 2.205.24 1.17-.87 1.545-1.966 1.41-.811-.18-1.26-.586-1.755-1.336l-1.83 1.051c.21.48.45.689.81 1.109 1.74 1.756 6.09 1.666 6.871-1.004.029-.09.24-.705.074-1.65l.046.067zm-8.983-7.245h-2.248c0 1.938-.009 3.864-.009 5.805 0 1.232.063 2.363-.138 2.711-.33.689-1.18.601-1.566.48-.396-.196-.597-.466-.83-.855-.063-.105-.11-.196-.127-.196l-1.825 1.125c.305.63.75 1.172 1.324 1.517.855.51 2.004.675 3.207.405.783-.226 1.458-.691 1.811-1.411.51-.93.402-2.07.397-3.346.012-2.054 0-4.109 0-6.179l.004-.056z" /></svg>
                        <svg aria-labelledby="simpleicons-css3-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title id="simpleicons-css3-icon">CSS3 icon</title><path d="M1.5 0h21l-1.91 21.563L11.977 24l-8.565-2.438L1.5 0zm17.09 4.413L5.41 4.41l.213 2.622 10.125.002-.255 2.716h-6.64l.24 2.573h6.182l-.366 3.523-2.91.804-2.956-.81-.188-2.11h-2.61l.29 3.855L12 19.288l5.373-1.53L18.59 4.414z" /></svg>
                    </div>
                </a>
            </div>

        </div>
    </div>
    <!-- Circle Animation and portal entry button -->



    <!-- Info Panel -->
    <div class="col s4">

        <div class="info_panel z-depth-1">
          
            <h5 class="info_panel_heading">New And Upcoming</h5>

            <div class="collection">

                <a href="#" class="collection-item">
                    <span class="new badge"></span>  <div class="panel_links">
                        <h6>HTML</h6>
                        <p>In this course we will learn the basics of the structured language Hyper Text Markup Language or (HTML)</p>
                    </div>
                </a>

                <a href="#" class="collection-item">
                    <span class="new badge"></span> <div class="panel_links">
                        <h6>CSS3 Basics</h6>
                        <p>What site is good with some sort of looks</p>
                    </div>
                </a>

                <a href="#" class="collection-item">
                    <span class="new badge"></span> <div class="panel_links">
                        <h6>JavaScript Introduction</h6>
                        <p>In this course we will go into a small dive in the world of JavaScript</p>
                    </div>
                </a>

            </div>

        </div>

    </div>
    <!-- Info Panel -->


</div>
  

WaMvTech/WaMvTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Comic Book Gallery</title>
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/portal.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>


    <nav>
        <div class="nav-wrapper">
            <a href="@Url.Action("Index","Landing")"class="brand-logo">Logo</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">     
            </ul>
        </div>
    </nav>

    <div class="container-fluid">

        @RenderBody()


        <!--Footer-->
            <footer>
                <p>&copy; @DateTime.Now.Year - Washington Military Veteran Tech</p>
            </footer>
        <!--Footer-->


    </div>


    <script type="text/javascript" src="js/materialize.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>